Adds description elements to charts.
ilios/ember-simple-charts pull request #1012
Opened 2023-02-08 22:18 UTC by stopfstedt

fixes #1011

2023-02-08 22:20 UTC, stopfstedt commented
@jrjohnson side-note: i left the color box chart out since i don't really know if a description here is even applicable. all the other ones are pretty clear-cut. pls let me know if you have any thoughts on that one.

2023-02-09 06:40 UTC, jrjohnson requested changes
I love this!

Can you also add this new chart data to the docs app. I'm not sure we need special documentation for this, but I think the chart data from the test app will make this feature more discoverable and easier to manually test since the docs app gets a preview rendering.

2023-02-09 06:40 UTC, jrjohnson commented on packages/test-app/tests/integration/components/simple-chart-pack-test.js
> +    //await pauseTest();
//

2023-02-09 18:04 UTC, stopfstedt commented on packages/test-app/tests/integration/components/simple-chart-pack-test.js
> +    //await pauseTest();
handled.

2023-02-09 18:05 UTC, stopfstedt commented
> I love this!
> 
> Can you also add this new chart data to the docs app. I'm not sure we need special documentation for this, but I think the chart data from the test app will make this feature more discoverable and easier to manually test since the docs app gets a preview rendering.

:100:  will update the docs app now.

2023-02-09 18:41 UTC, jrjohnson approved these changes

2023-02-09 19:28 UTC, merged